# Generated by Django 5.2.13 on 2026-05-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_alter_emailsearchresults_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
