# Generated by Django 5.2.13 on 2026-05-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_fix_phone_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersinputlogs',
            table='user_input_logs',
        ),
    ]
