# Generated by Django 5.2.13 on 2026-05-01 09:32

import checker.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_alter_usersinputlogs_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousmonitoring',
            name='input_value',
            field=checker.encryption.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emailsearchresults',
            name='email',
            field=checker.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phonesearchresults',
            name='phone_number',
            field=checker.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='input_value',
            field=checker.encryption.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usersinputlogs',
            name='search_query',
            field=checker.encryption.EncryptedCharField(max_length=500),
        ),
    ]
