# Generated by Django 5.2.13 on 2026-05-01 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_alter_continuousmonitoring_input_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkWebResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='dark_web', max_length=20)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('found_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='checker.user')),
            ],
            options={
                'db_table': 'dark_web_results',
                'managed': True,
            },
        ),
    ]
