name: Deploy OSINT Backend to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd ~/osint/osint_backend
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          pkill -HUP gunicorn
          pkill -9 celery || true
          nohup celery -A osint_backend worker -l info > celery.log 2>&1 &
